name: Swift

on:
  push:
    branches:
      - main
      - develop
      - "release/*"
      - "hotfix/*"
  pull_request:
    branches:
      - main
      - develop

env:
  DEVELOPER_DIR: /Applications/Xcode_16.2.app

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
